### ISSUE TITLE
くじ引きのモーダル化

### ISSUE THREAD

**Issue by ykzts** [inabagumi/inaba-jinja#875]
#198 と #235 の統合

くじ引きボタンを押した際に別のページに移動させるのではなくモーダル表示をさせるようにしたい。

ただしくじの進行状況に応じて `router.push` を使ってURLの変更は行うようにすることによってURLをシェアしてもらった際のアクセスがトップに集約されないようにする。

**Comment by haohanyang** [comment]
I recommend showing the process of the lottery without extra route and notifying the results in modal component

**Comment by ykzts** [comment]
Yes, I'm working on it.
